sonar.projectKey=pharma-dashboard
sonar.organization=your-org-name
sonar.host.url=https://sonarcloud.io
sonar.login=${040b4f18d6f06371d3883519d59a0f6b9e1c8bcf}

sonar.sources=src
sonar.exclusions=**/*.spec.ts,**/*.test.ts
