name: Full DevOps Pipeline

on:
  push:
    branches: [main]

jobs:
  devsecops-pipeline:
    runs-on: ubuntu-latest

    steps:
      # -------- CHECKOUT CODE --------
      - name: Checkout code
        uses: actions/checkout@v3

      # -------- SETUP NODE --------
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Node dependencies
        run: npm ci

      - name: Run tests with coverage
        run: npm test -- --coverage || true

      # -------- TRIVY SCAN --------
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: .

      # -------- ANSIBLE DEPLOY --------
      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Add SSH key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Deploy with Ansible
        run: ansible-playbook -i inventory.ini deploy.yml --private-key key.pem
